### ISSUE TITLE
Progressive alpha scissoring not happening

### ISSUE THREAD

**Issue by comfortmfune** [nekotogd/Godot_BotW_Explosion#1]
So I'm using the shader but the particle just isn't disintegrating during its lifetime. It does flicker to the noise but it doesn't disintegrate over the particles life, it only changes color but that happens in the process material. Any help??

I'm using Godot 3.5, yes old news. I'm not all that fluent in shader math so I just followed along to the tutorial hoping to start teaking it once it's working.

**Comment by comfortmfune** [comment]
Alright I figured it out

**Comment by nekotogd** [comment]
Oh uhh, cool!

How did you fix it? Just in case someone else looks at this issue with the same problem.

**Comment by comfortmfune** [comment]
Actually I hadn't setup all 3 color_ramp colors, it just looked that way when I set them up without using the array drop down list that's provided, so I practically set 2 colors and just reset/replaced the second one thinking I've added another.

Thanks, you can't really make a lot of games without explosions and as a shader noob it's rough.
